### ISSUE TITLE
Exception on Windows

### ISSUE THREAD

**Issue by philllies** [raph-amiard/sublime-typescript#4]
Hi,

I am trying to get the plugin working on Windows and get the following error:

```
OUT OF INIT ASYNC
Exception in thread Thread-3:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\threading.py", line 484, in run
  File ".\typescript.py", line 199, in init_view_async
  File ".\typescript.py", line 186, in init_file
  File ".\typescript.py", line 163, in serv_add_file
  File ".\typescript.py", line 159, in msg
  File ".\json\__init__.py", line 307, in loads
  File ".\json\decoder.py", line 319, in decode
  File ".\json\decoder.py", line 338, in raw_decode
ValueError: No JSON object could be decoded
```

I added node to my PATH and also tried manually setting node_path in the settings, but no luck so far. Do you have any idea how to work around this issue?

**Comment by raph-amiard** [comment]
Hey, i'm gonna test the plugin out on windows and i'll keep you updated shortly ! probably tomorow afternoon

**Comment by philllies** [comment]
Great, looking forward!
BTW: I used cygwin to run make, which led to unix paths in the settings.py - I adjusted them manually directly in the file.

**Comment by kube** [comment]
I have the same problem after compilation with the make from GNU utilities for Win32, which is not the make from Cygwin or MinGW.

I read the issue of futuresplash, and added in typescript.sublime-settings

``` javascript
"node_path" : "c:/Program Files/nodejs/node.exe"
```

And also edited settings.py like this : 

``` python
PLUGIN_PATH = "c:/Users/KUBE/AppData/Roaming/Sublime Text 2/Packages/sublime-typescript"
```

And now when I open a .ts file I have a node console window launched which closes instantaneously, so I think that my node_path is well entered, but nothing works and I still have the : 

``` text
Loading typescript plugin /
```

In my console I have this : 

``` text
OUT OF INIT ASYNC
Exception in thread Thread-3:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\threading.py", line 484, in run
  File ".\typescript.py", line 199, in init_view_async
  File ".\typescript.py", line 186, in init_file
  File ".\typescript.py", line 163, in serv_add_file
  File ".\typescript.py", line 159, in msg
  File ".\json\__init__.py", line 307, in loads
  File ".\json\decoder.py", line 319, in decode
  File ".\json\decoder.py", line 338, in raw_decode
ValueError: No JSON object could be decoded
```

which is exactly the same Exception as above.

I am using Sublime Text 2 Build 2217 on Windows 8.

**Comment by raph-amiard** [comment]
Hi there, just to tell you guys that :
- I've looked into the issue. The problem seems to be in the Popen call to the node server in the python plugin. I think it is returning immediately. Must be something related to piping stdin/stdout under Windows.
- Unfortunately for a couple of reasons, i won't be able to look into the issue right now. I have a ton of work on my arms and my workflow under Windows sucks so it's taking me ages to do the simplest of things.

I'll get to fix that, i just don't know when, so if somebody wants to investigate feel free . The problem should be easily reproducible in a simpler form :
1. Make a node process reading and writing values out of stdin/stdout with the readline module
2. Run it from python with popen, send and receive values
3. Make it work :)

**Comment by philllies** [comment]
Hi,
I had a look at it. It seems that if main.js running in node writes to stderr, node terminates for some reason. To prevent this, you have to explicitly set stderr when spawing a subprocess with Popen.

Here are the steps to make the plugin work on Windows:.
1. Run the Makefile
2. Make sure the PLUGIN_PATH in core/settings.py is set correctly (e.g. PLUGIN_PATH = "C:\Users\test\AppData\Roaming\Sublime Text 2\Packages\sublime-typescript"
3. Open typescript.py
- add "import os" to the import declarations
- replace def init_async() within the PluginInstance constructor with this code

```
def init_async():
    loading_files.inc()
    errorlog = open(os.devnull, 'w')
    self.p = Popen([get_node_path(), plugin_file("bin/main.js")], stderr=errorlog, stdin=PIPE, stdout=PIPE)
    self.serv_add_file(plugin_file("bin/lib.d.ts"))
    errorlog.close();
    loading_files.dec()
    print "OUT OF INIT ASYNC"
    self.init_sem.release()
```

You can also set errorlog to some log file, of course.
4. Done :)

**Comment by kube** [comment]
Good Job.

I just added this to typescript.py to hide the NodeJS window :
(http://stackoverflow.com/questions/1016384/cross-platform-subprocess-with-hidden-window) 

``` python
import subprocess
```

At the beginning of init_async() :

``` python
startupinfo = None
if os.name == 'nt':
        startupinfo = subprocess.STARTUPINFO()
        startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
```

and the Popen line becomes :

``` python
self.p = Popen([get_node_path(), plugin_file("bin/main.js")], stderr=errorlog, stdin=PIPE, stdout=PIPE, startupinfo=startupinfo)
```

**Comment by raph-amiard** [comment]
Hey guys, you rock, thank you for this :)

I'm gonna adapt those changes to the master branch, so that it works out of the box on every OS. Also, i'm gonna think on a simpler way to install under windows, because asking people to have Cygwin is not clean IMHO.

Thank you again !

**Comment by raph-amiard** [comment]
Hey, i pushed a fix, the plugin should work under windows now, although the installation process is still tedious. Tell me if it works as is, because i don't have access to a windows machine right now, i'll work on simplifying the installation process.

**Comment by kube** [comment]
Still one error remains. settings.py still has unix-like path :

``` python
PLUGIN_PATH = "/c/Users/KUBE/AppData/Roaming/Sublime Text 2/Packages/sublime-typescript"
```

**Comment by raph-amiard** [comment]
Yes, i know. I have no idea as to how to resolve that at the moment. I'm trying to fix that and remove the cygwin dependency at the same time

**Comment by raph-amiard** [comment]
There are a couple of ways to get the path of the executing file in python. The problem is that none of them works when you're running a py file inside Sublime Text.

I've tried [this](http://stackoverflow.com/questions/50499/in-python-how-do-i-get-the-path-and-name-of-the-file-that-is-currently-executin) and [that](http://stackoverflow.com/questions/7162366/get-location-of-the-py-source-file) already. If any of you has a good idea to replace my dirty Makefile hack under windows, i'm all ears. I'll then be ready to transport all the make process into the plugin directly.

**Comment by kube** [comment]
``` makefile
core/settings.py:
ifeq ($(CURDIR),)
    echo "PLUGIN_PATH = \"`pwd`\"" >> core/settings.py
else
    echo "PLUGIN_PATH = \"$(CURDIR)\"" >> core/settings.py
endif
```

It works on Windows for me, not sure it will work on Linux.

**Comment by kube** [comment]
I created a file _makefile.py_ which does exactly what the Makefile does :

``` python
import os
import subprocess
import shlex


def make_all():
   main_js_compile()
   plugin_path_to_settings()
   lib_dts()
   typescript_js()
   typescript_services()

def main_js_compile():
   # Compile main.js
   if os.name == 'nt':
      startupinfo = subprocess.STARTUPINFO()
      startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
   subprocess.Popen(shlex.split("node lib/typescript/bin/tsc.js src/ts/main.ts --out bin/main.js"), startupinfo=startupinfo)

def plugin_path_to_settings():
   # Write PLUGIN PATH in settings.py
   if os.name == "nt":
      command = "echo PLUGIN_PATH = \"%CD%\" >> core/settings.py"
   else:
      command = "echo \"PLUGIN_PATH = \\\"`pwd`\\\"\" >> core/settings.py"
   os.system(command)

def lib_dts():
   os.system("cp lib/typescript/bin/lib.d.ts bin/")

def typescript_js():
   os.system("cp lib/typescript/bin/typescript.js bin/")

def typescript_services():
   os.system("cp lib/typescript/bin/typescriptServices.js bin/")

def bin():
   os.system("mkdir bin")

def clean():
   os.system("rm -rf bin/*")
   os.system("rm -rf core/settings.py")
```

I don't know if everything will be necessary but it works on Windows (and should work on Unix), just I'm not sure about the PLUGIN_PATH part for Unix.
And I would like to know how to put all these methods in an object. (Never used Python, don't know how to do this, without a class I mean)

**Comment by raph-amiard** [comment]
Haha talk about duplicated effort :) Just finished my own version of the thing :)

It is a bit different too because it uses the settings file for the plugin path, does the compilation asynchronously, and doesn't rely on shell commands for plugin path, since that won't work on unix if you launch sublime from the shell, in a place which is not the plugin directory.

It is supposed to do everything when the plugin is first ran, so as to avoid any installation step. 

I'm gonna push it very soon, i'd appreciate if you tell me if it works ! Thanks for your effort, really appreciate it :)

**Comment by raph-amiard** [comment]
Ok, i just pushed, testing the fix under windows and telling you if it works

**Comment by kube** [comment]
Yeah I knew my version kinda dirty. :)
I update, and try immediately.

**Comment by raph-amiard** [comment]
Wait 2 secs, just turns out my version has bugs under windows ^^ pushing a fixed version ASAP

**Comment by raph-amiard** [comment]
Ok it should work, just have to fix the node window popping up on first run, but appart from that it should work just fine

**Comment by kube** [comment]
Ok, I was going to post the error. ;)
I update again.

**Comment by raph-amiard** [comment]
Ok the version i pushed was working, but recompiling the plugin at every startup because i wasn't saving the settings, it should be good now :) sorry for all the back and forth !

**Comment by kube** [comment]
Still have an error :

``` text
Exception in thread Thread-1:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\threading.py", line 484, in run
  File ".\typescript.py", line 41, in install_helper
    install.compile_plugin(plugin_path)
  File ".\core\install.py", line 56, in compile_plugin
    subprocess.call([get_node_path(), plugin_file("lib/typescript/bin/tsc.js"), plugin_file("src/ts/main.ts"), "--out", plugin_file("bin/main.js")])
  File ".\core\install.py", line 13, in get_node_path
    if ts_settings.has("node_path"):
RuntimeError: Must call on main thread, consider using sublime.set_timeout(function, timeout)
```

**Comment by raph-amiard** [comment]
Hey, your traceback indicates to me that you didn't pull the last version, pull again and tell me if it's good now

**Comment by kube** [comment]
Oops. Sorry. I used the bad command. :)
Everything works perfectly !

**Comment by raph-amiard** [comment]
Great ! This thing is now truely cross platform :) Thanks for your help in this !

**Comment by kube** [comment]
Thank you for taking the time to fix all this, I saw you were using Vim now.
Maybe you should submit your plugin to the Package Control ? Now that there is no need to use _make_ :)

**Comment by raph-amiard** [comment]
Hey, no problem, it's still my project, even if i don't use it at the moment, i plan to later :) I'm waiting to see where Sublime Text goes before investing more time in it, but i'll keep doing maintenance on it.

I don't know very well how to submit a package for the package manager, i'm gonna document myself on it :)
